### ISSUE TITLE
Cant Play a specific song - Internal Server Error: Exception in ASGI application

### ISSUE THREAD

**Issue by justinh998** [DavidBerdik/YouTube-Stream-Repeater#4]
Hi
I haven't had a very close look at the whole thing myself yet, but I wanted to report it. It looks to me bsi now as if the problem comes from the starlett modull.
Maybe there are problems because the URL starts with - , but I personally don't believe in that.
Here is my stacktrace (above you can also see what I tried to play)

```[-axvKh-m4rY]: requested with format bestaudio and subs None, configuring...
[-axvKh-m4rY]: sending stream
[-axvKh-m4rY]: stream will be sent as is (bestaudio)
[-axvKh-m4rY]: end of data (no error reported)
cleanup[-axvKh-m4rY]: killing downloader process (PID: 191)
INFO:     84.171.122.154:56565 - "GET /dl/-axvKh-m4rY?f=bestaudio HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 377, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/user/app/./server.py", line 23, in api_dl
    first_chunk = await stream.__anext__() # peek first chunk
StopAsyncIteration
```

**Comment by DavidBerdik** [comment]
I was able to reproduce the issue as well, but I have not started investigating what is causing it.

**Comment by justinh998** [comment]
Hi 
I started looking at this tonight, I think youtube-dlp has a problem with the - , but that should be fixable, I'm building stream_from_yt (line 31 in the Util/Stream.py).
But I noticed something that makes no sense in my world. 
There is the nice function stream_from_yt:
``async def stream_from_yt(id: str, format: str = "best", sl: str = None):
    print(f"[{id}]: requested with format {format} and subs {sl}, configuring...")
    args = [
        # request to download with video ID
        "yt-dlp", id, 
        # output to stdout (needed for streaming)
        "-o", "-", 
        # specify output format
        "-f", format,
        # matroska just allows every format possible
        "--merge-output-format", "mkv"
    ]``


which expects some transfer values, which it also receives when it is executed: 
``@app.get("/dl/{video_id}")
async def api_dl(
    video_id: str,   # the video's ID (watch?v=<this>)
    f: str = "best",# format 
  sl: str = None,  # subtitle language to embed
):
    stream = stream_from_yt(video_id, f, sl)  ``

"best" is passed to the function as the value for format, but the function then assembles something like this:

``
yt-dlp RqplzrM6Im4 -o - -f bestaudio --merge-output-format mkv

``

I don't quite understand how the function suddenly goes from best to bestaudio , that shouldn't be possible, since the function is only passed best and that is not combined with the word audio in the function.

**Comment by DavidBerdik** [comment]
Thanks for taking the time to look into this for me! I really appreciate it.

I'm a bit confused by your explanation, but I will add that I'm not sure that `yt-dlp` is the source of the problem. The reason I doubt that it is is because when I try to use it directly from the command prompt, it downloads the video properly.

```
C:\Users\David\Downloads>yt-dlp https://www.youtube.com/watch?v=-axvKh-m4rY -f best
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[youtube] Extracting URL: https://www.youtube.com/watch?v=-axvKh-m4rY
[youtube] -axvKh-m4rY: Downloading webpage
[youtube] -axvKh-m4rY: Downloading ios player API JSON
[youtube] -axvKh-m4rY: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "-axvKh-m4rY")
[youtube] -axvKh-m4rY: Downloading player fa761abe
[youtube] -axvKh-m4rY: Downloading m3u8 information
[info] -axvKh-m4rY: Downloading 1 format(s): 18
[download] Destination: Lieder, die wie Brücken sind [-axvKh-m4rY].mp4
[download] 100% of    3.93MiB in 00:00:01 at 2.81MiB/s
```

If it was a problem with `yt-dlp` I would expect this behavior to be reproduced when using it on the command line as well.

**Comment by justinh998** [comment]
The problem is solved, the problem was with youtube dlp, I'll explain it to you: 
The program has so far created the following query for yt-dlp: 
yt-dlp RqplzrM6Im4 -o - -f bestaudio --merge-output-format mkv( the query that you executed manually in your console above works because it is different from the one generated by the program.
The program does not use full links but only ids.
Furthermore you forgot some options e.g. -o -merge output mkw.
But they don't matter, the important thing is that you eliminate problems by using the full link.
Youtube Dlp thinks the video ID is an argument (which it apparently can't be) because it starts with a hyphen like real arguments, so the solution is simply to use the full link. It will look like yt-dlp https://youtube.com/watch?v=-axvKh-m4rY -o - -f bestaudio --merge-output-format mkv
The whole thing also works if there is a line in front of it, for example. 
I have implemented this 
[here](https://github.com/justinh998/YouTube-Stream-Repeater/commit/5aa9ff2f48a9cddeff7ea04b91f116a253afff42).
But later I will replace this long youtube .com watch string with youtube.be/id. It's shorter and clearer, I'll have to see if I can do a merge reuqest when I've changed it.

**Comment by DavidBerdik** [comment]
That's incredibly fascinating but also incredibly obvious in hindsight. 😆

Anyway, yes, if you are willing to submit a PR for this, I would really appreciate it!
